import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import ClientLayout from "@/components/ClientLayout";
import { ToastContainer } from "react-toastify";
import "react-date-range/dist/styles.css"; // Main style file
import "react-date-range/dist/theme/default.css"; // Theme CSS file
import "@/assets/css/react-toastify.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "AUTO Trade",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				{/* Flowbite CSS CDN */}
				<link
					href="https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.min.css"
					rel="stylesheet"
				/>
			</head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased
				font-['Inter'] text-gray-900`}
			>
				<ClientLayout>{children}</ClientLayout>
				<ToastContainer />

				{/* Load Flowbite JS */}
				<Script
					src="https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.min.js"
					strategy="beforeInteractive" // Ensures it's loaded before hydration
				/>
			</body>
		</html>
	);
}
